#ifndef LIGHTMODBUS_ESP_CONFIG_H
#define LIGHTMODBUS_ESP_CONFIG_H

#include "sdkconfig.h"

#define LIGHTMODBUS_SLAVE
#define LIGHTMODBUS_F01S
#define LIGHTMODBUS_F02S
#define LIGHTMODBUS_F03S
#define LIGHTMODBUS_F04S
#define LIGHTMODBUS_F05S
#define LIGHTMODBUS_F06S
#define LIGHTMODBUS_F15S
#define LIGHTMODBUS_F16S
#define LIGHTMODBUS_F22S

#define LIGHTMODBUS_MASTER
//#define LIGHTMODBUS_MASTER_OMIT_REQUEST_CRC
#define LIGHTMODBUS_F01M
#define LIGHTMODBUS_F02M
#define LIGHTMODBUS_F03M
#define LIGHTMODBUS_F04M
#define LIGHTMODBUS_F05M
#define LIGHTMODBUS_F06M
#define LIGHTMODBUS_F15M
#define LIGHTMODBUS_F16M
#define LIGHTMODBUS_F22M

#endif
